arm osx migration
conda-forge/xorg-libxtst-feedstock pull request #8
Opened 2021-05-18 21:40 UTC by Tobias-Fischer

Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

2021-05-18 21:41 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipe```) and found it was in an excellent condition.

2021-05-18 22:00 UTC, Tobias-Fischer commented
Hi @xorg-libxtst this is ready to be merged. Thanks!

2021-05-18 22:00 UTC, Tobias-Fischer commented
Fix #7

2021-05-19 12:59 UTC, pkgw requested changes
Thanks for fixing up the bot PR! We've been using a slightly different pattern for the libx11 pinning, which I think is a bit more future-proof — see below.

2021-05-19 12:59 UTC, pkgw commented on recipe/meta.yaml
> +    - xorg-libx11 1.7.*  # [osx and arm64]
We have been using slightly different boilerplate to do the libx11 pinning, namely:

https://github.com/conda-forge/xorg-libxfixes-feedstock/blob/0b7e78d73fbab3f3d93716b54a618e8b3fb4d055/recipe/meta.yaml#L41-L43

in the `host` section and and

https://github.com/conda-forge/xorg-libxfixes-feedstock/blob/0b7e78d73fbab3f3d93716b54a618e8b3fb4d055/recipe/meta.yaml#L49

in the `run` section. This format should be more future-proof for changes to the pinning. Would you mind changing this section to use the same template, including the same explanatory comment?

2021-05-19 21:39 UTC, Tobias-Fischer commented
Thanks for the review @pkgw - it should be ready to go now.

2021-05-20 12:57 UTC, pkgw approved these changes
Thanks!

2021-05-20 12:57 UTC, merged